name: Continuous Integration
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17', '19' ]
    name: Build with Java ${{ matrix.Java }}
    steps:
      - name: "Checkout sources"
        uses: actions/checkout@v3
      - name: "Setup Java"
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: ${{ matrix.java }}
      - name: "Build"
        run: java build/build.java
