name: Continuous Integration
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '25' ]
    name: Build with Java ${{ matrix.Java }}
    steps:
      - name: "Checkout sources"
        uses: actions/checkout@v5
      - name: "Setup Java"
        uses: actions/setup-java@v5
        with:
          distribution: 'oracle'
          java-version: ${{ matrix.java }}
      - name: "Build"
        run: java build/build.java
